# Change these first
owner: nerdyfactory # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Nf website
    url: https://nerdyfactory.com
  - name: Nf website - KO
    url: https://nerdyfactory.com/ko/

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://nerdyfactory.com/imgs/nerdyfactory_logo.png
  name: Nf status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
